In [3]:
import pandas as pd
import math
import networkx as nx
import matplotlib.pyplot as plt
import numpy as np

In [9]:
path = 'C:/Users/sol/Documents/01-bikes_bogota/'

In [10]:
nodes=pd.read_csv(path + 'nodes_all.csv')
links=pd.read_csv(path + 'links_all.csv')

In [20]:
nodes.loc[:,'tuple'] = list(zip(nodes['Latitude'].tolist(),nodes['Longitude'].tolist()))

In [21]:
# Nodes are the characteristics of the tower
nodes.head(2)

,id,Label,income_level,wstrato,pop,Longitude,Latitude,tuple
0,1.0,1.0,2.0,3.000000,17197.0,-74.1205,4.61808,"(4.61808, -74.1205)"
1,2.0,2.0,1.0,1.860132,24609.0,-74.1327,4.56084,"(4.56084, -74.1327)"

In [22]:
links.head(5)

   Source  Target     Weight  income_level  wstrato_o      Type
0   265.0   455.0  28.228165           1.0   2.000000  Directed
1   448.0   455.0  24.726087           2.0   3.000000  Directed
2    13.0   455.0  22.728797           1.0   1.963427  Directed
3   272.0   455.0  33.571853           1.0   2.000000  Directed
4   264.0   455.0  32.409447           2.0   3.030184  Directed

In [23]:
merge_source=pd.merge(links,nodes[['id','Latitude','Longitude']],left_on='Source',right_on='id',how='left')

In [24]:
merge_source.head()

,Source,Target,Weight,income_level,wstrato_o,Type,id,Latitude,Longitude
0,265.0,455.0,28.228165,1.0,2.000000,Directed,265.0,4.73042,-74.1060
1,448.0,455.0,24.726087,2.0,3.000000,Directed,448.0,4.60370,-74.0725
2,13.0,455.0,22.728797,1.0,1.963427,Directed,13.0,4.55389,-74.0994
3,272.0,455.0,33.571853,1.0,2.000000,Directed,272.0,4.73972,-74.1073
4,264.0,455.0,32.409447,2.0,3.030184,Directed,264.0,4.74534,-74.0950

In [25]:
merge_source.rename(columns={'Latitude': 'source_lat', 'Longitude': 'source_lon'},inplace=True)

In [26]:
merge_target=pd.merge(merge_source,nodes[['id','Latitude','Longitude']],left_on='Target',right_on='id',how='left')

In [27]:
merge_target.rename(columns={'Latitude': 'target_lat', 'Longitude': 'target_lon'},inplace=True)

In [28]:
links=merge_target.drop(['id_x','id_y'],axis=1)

## Graph, all trips

In [29]:
G=nx.DiGraph()

In [30]:
G.add_nodes_from(nodes['id'].tolist(),pos=nodes['tuple'],strata=nodes['wstrato'])

In [31]:
G.add_weighted_edges_from(zip(links['Source'].tolist(),links['Target'].tolist(),links['Weight'].tolist()))

In [32]:
pos=dict(zip(nodes['id'], nodes['tuple']))

In [133]:
plt.figure(figsize=(20,20))
nx.draw(G,pos,node_size=1,figsize=(20,20))

### Modularity Maximization

In [33]:
net=G.to_undirected()

In [36]:
# !pip install python-louvain

In [40]:
import community

#first compute the best partition
partition = community.best_partition(net)

#drawing
size = float(len(set(partition.values())))
count = 0
plt.figure(figsize=(15,15))
for com in set(partition.values()) :
    count = count + 1
    list_nodes = [nodes for nodes in partition.keys()
                                if partition[nodes] == com]
    nx.draw_networkx_nodes(net, pos, list_nodes,
                                node_color = np.random.uniform(0.25,0.95,3))

nx.draw_networkx_edges(net, pos)
plt.show()

In [41]:
partition

{1.0: 0,
 2.0: 1,
 3.0: 1,
 4.0: 1,
 5.0: 1,
 6.0: 1,
 7.0: 2,
 8.0: 1,
 9.0: 2,
 10.0: 0,
 11.0: 2,
 12.0: 2,
 13.0: 2,
 14.0: 2,
 15.0: 0,
 16.0: 2,
 17.0: 2,
 18.0: 1,
 19.0: 1,
 20.0: 1,
 21.0: 2,
 22.0: 1,
 23.0: 0,
 24.0: 2,
 25.0: 1,
 26.0: 0,
 27.0: 1,
 28.0: 1,
 29.0: 3,
 30.0: 0,
 31.0: 1,
 32.0: 1,
 33.0: 1,
 34.0: 2,
 35.0: 2,
 36.0: 1,
 37.0: 2,
 38.0: 1,
 39.0: 2,
 40.0: 1,
 41.0: 1,
 42.0: 1,
 43.0: 0,
 44.0: 2,
 45.0: 2,
 46.0: 1,
 47.0: 2,
 48.0: 0,
 49.0: 1,
 50.0: 4,
 51.0: 1,
 52.0: 1,
 53.0: 1,
 54.0: 2,
 55.0: 3,
 56.0: 3,
 57.0: 1,
 58.0: 0,
 59.0: 1,
 61.0: 2,
 62.0: 0,
 63.0: 0,
 64.0: 2,
 65.0: 2,
 66.0: 0,
 67.0: 2,
 68.0: 2,
 69.0: 0,
 70.0: 2,
 71.0: 0,
 72.0: 2,
 73.0: 0,
 74.0: 2,
 75.0: 0,
 76.0: 3,
 77.0: 2,
 78.0: 2,
 81.0: 4,
 83.0: 4,
 87.0: 4,
 88.0: 4,
 89.0: 4,
 90.0: 4,
 91.0: 4,
 92.0: 4,
 93.0: 4,
 94.0: 4,
 95.0: 4,
 96.0: 4,
 97.0: 4,
 98.0: 4,
 99.0: 4,
 100.0: 4,
 101.0: 4,
 102.0: 4,
 103.0: 4,
 104.0: 4,
 106.0: 4,
 107.0: 2,
 108.0: 4,
 109.0: 4,
 110.0: 4,
 111.0: 4,
 112.0: 4,
 113.0: 4,
 114.0: 4,
 115.0: 4,
 116.0: 4,
 117.0: 4,
 119.0: 5,
 120.0: 4,
 124.0: 4,
 125.0: 4,
 126.0: 4,
 127.0: 4,
 128.0: 4,
 129.0: 4,
 130.0: 4,
 131.0: 4,
 132.0: 4,
 133.0: 4,
 134.0: 4,
 135.0: 4,
 136.0: 4,
 137.0: 4,
 138.0: 4,
 139.0: 1,
 140.0: 0,
 141.0: 4,
 142.0: 4,
 143.0: 1,
 144.0: 4,
 145.0: 4,
 146.0: 4,
 147.0: 1,
 148.0: 1,
 149.0: 4,
 150.0: 4,
 151.0: 4,
 152.0: 4,
 153.0: 4,
 154.0: 4,
 155.0: 2,
 157.0: 2,
 158.0: 4,
 159.0: 3,
 160.0: 4,
 162.0: 1,
 164.0: 4,
 166.0: 4,
 167.0: 4,
 168.0: 4,
 169.0: 4,
 170.0: 4,
 171.0: 4,
 172.0: 4,
 173.0: 4,
 174.0: 1,
 175.0: 4,
 176.0: 4,
 177.0: 4,
 178.0: 4,
 179.0: 4,
 180.0: 4,
 181.0: 4,
 182.0: 4,
 183.0: 4,
 184.0: 4,
 185.0: 4,
 186.0: 4,
 187.0: 4,
 188.0: 2,
 189.0: 4,
 191.0: 4,
 192.0: 4,
 193.0: 4,
 194.0: 4,
 195.0: 4,
 196.0: 4,
 198.0: 4,
 199.0: 4,
 200.0: 5,
 203.0: 5,
 204.0: 5,
 206.0: 5,
 207.0: 5,
 208.0: 5,
 209.0: 5,
 210.0: 5,
 211.0: 5,
 213.0: 5,
 214.0: 5,
 215.0: 5,
 216.0: 5,
 217.0: 5,
 218.0: 5,
 219.0: 0,
 220.0: 5,
 221.0: 5,
 222.0: 5,
 223.0: 5,
 224.0: 5,
 225.0: 5,
 226.0: 5,
 227.0: 5,
 228.0: 1,
 229.0: 5,
 230.0: 5,
 231.0: 5,
 232.0: 5,
 233.0: 5,
 235.0: 5,
 236.0: 5,
 237.0: 5,
 239.0: 5,
 241.0: 0,
 244.0: 5,
 245.0: 5,
 247.0: 0,
 248.0: 5,
 249.0: 5,
 250.0: 5,
 251.0: 5,
 252.0: 5,
 253.0: 5,
 255.0: 5,
 262.0: 5,
 263.0: 4,
 264.0: 4,
 265.0: 4,
 266.0: 4,
 267.0: 4,
 268.0: 4,
 269.0: 4,
 271.0: 4,
 272.0: 4,
 273.0: 4,
 274.0: 4,
 275.0: 4,
 276.0: 4,
 277.0: 4,
 278.0: 4,
 280.0: 4,
 281.0: 4,
 282.0: 4,
 283.0: 4,
 284.0: 6,
 285.0: 4,
 286.0: 5,
 287.0: 5,
 288.0: 5,
 289.0: 5,
 290.0: 5,
 291.0: 5,
 292.0: 5,
 293.0: 5,
 294.0: 5,
 295.0: 4,
 296.0: 5,
 297.0: 5,
 298.0: 0,
 299.0: 5,
 300.0: 0,
 301.0: 4,
 302.0: 6,
 303.0: 0,
 309.0: 0,
 310.0: 0,
 311.0: 0,
 312.0: 0,
 313.0: 0,
 314.0: 0,
 315.0: 0,
 316.0: 0,
 317.0: 0,
 318.0: 0,
 319.0: 0,
 320.0: 0,
 321.0: 0,
 322.0: 0,
 323.0: 0,
 324.0: 1,
 325.0: 1,
 326.0: 0,
 327.0: 0,
 328.0: 0,
 329.0: 1,
 330.0: 0,
 331.0: 0,
 332.0: 1,
 333.0: 0,
 334.0: 0,
 335.0: 0,
 336.0: 7,
 337.0: 1,
 338.0: 1,
 339.0: 0,
 340.0: 0,
 341.0: 0,
 342.0: 0,
 343.0: 0,
 344.0: 0,
 345.0: 0,
 346.0: 0,
 347.0: 0,
 348.0: 0,
 349.0: 0,
 350.0: 0,
 351.0: 0,
 352.0: 0,
 353.0: 0,
 354.0: 0,
 355.0: 0,
 356.0: 0,
 357.0: 0,
 358.0: 0,
 359.0: 2,
 360.0: 4,
 361.0: 0,
 362.0: 0,
 363.0: 0,
 364.0: 0,
 365.0: 0,
 366.0: 0,
 367.0: 0,
 368.0: 2,
 369.0: 0,
 370.0: 0,
 371.0: 0,
 372.0: 5,
 375.0: 2,
 376.0: 1,
 377.0: 1,
 378.0: 1,
 379.0: 4,
 380.0: 3,
 381.0: 4,
 382.0: 3,
 383.0: 4,
 384.0: 4,
 385.0: 4,
 386.0: 1,
 387.0: 4,
 388.0: 5,
 389.0: 4,
 390.0: 4,
 391.0: 4,
 392.0: 4,
 393.0: 0,
 394.0: 1,
 395.0: 2,
 396.0: 4,
 397.0: 4,
 398.0: 2,
 399.0: 4,
 400.0: 5,
 401.0: 4,
 402.0: 4,
 403.0: 4,
 404.0: 4,
 405.0: 7,
 406.0: 2,
 407.0: 5,
 408.0: 2,
 409.0: 4,
 410.0: 4,
 411.0: 5,
 412.0: 3,
 413.0: 4,
 414.0: 2,
 417.0: 2,
 418.0: 0,
 419.0: 4,
 420.0: 5,
 421.0: 4,
 422.0: 4,
 423.0: 4,
 424.0: 4,
 425.0: 5,
 426.0: 4,
 427.0: 4,
 428.0: 4,
 429.0: 5,
 430.0: 1,
 431.0: 4,
 432.0: 5,
 433.0: 7,
 434.0: 0,
 435.0: 1,
 436.0: 4,
 437.0: 4,
 438.0: 3,
 439.0: 0,
 441.0: 1,
 442.0: 5,
 443.0: 2,
 446.0: 2,
 447.0: 2,
 448.0: 0,
 449.0: 2,
 450.0: 5,
 451.0: 2,
 452.0: 2,
 453.0: 2,
 454.0: 2,
 455.0: 2,
 456.0: 2,
 457.0: 2,
 459.0: 2,
 460.0: 2,
 461.0: 5,
 462.0: 2,
 463.0: 1,
 464.0: 1,
 465.0: 2,
 468.0: 2,
 469.0: 1,
 471.0: 2,
 472.0: 2,
 473.0: 2,
 474.0: 1,
 475.0: 0,
 477.0: 2,
 481.0: 3,
 482.0: 2,
 483.0: 2,
 484.0: 4,
 485.0: 1,
 489.0: 2,
 491.0: 2,
 492.0: 2,
 493.0: 4,
 495.0: 1,
 496.0: 5,
 497.0: 2,
 498.0: 3,
 500.0: 2,
 501.0: 1,
 502.0: 2,
 503.0: 2,
 504.0: 0,
 505.0: 2,
 506.0: 2,
 507.0: 0,
 508.0: 0,
 509.0: 2,
 510.0: 2,
 511.0: 2,
 512.0: 2,
 513.0: 0,
 514.0: 2,
 515.0: 0,
 516.0: 0,
 518.0: 1,
 519.0: 7,
 522.0: 4,
 523.0: 7,
 524.0: 7,
 525.0: 7,
 526.0: 7,
 527.0: 0,
 528.0: 7,
 529.0: 7,
 530.0: 7,
 531.0: 2,
 532.0: 0,
 533.0: 7,
 534.0: 7,
 535.0: 0,
 536.0: 7,
 537.0: 4,
 538.0: 7,
 539.0: 7,
 540.0: 0,
 541.0: 0,
 542.0: 4,
 543.0: 5,
 544.0: 1,
 545.0: 3,
 546.0: 1,
 547.0: 2,
 548.0: 4,
 549.0: 4,
 550.0: 4,
 551.0: 2,
 552.0: 0,
 553.0: 4,
 554.0: 5,
 555.0: 4,
 556.0: 1,
 557.0: 1,
 558.0: 1,
 559.0: 4,
 560.0: 4,
 561.0: 4,
 562.0: 5,
 563.0: 2,
 564.0: 0,
 565.0: 2,
 566.0: 4,
 567.0: 2,
 570.0: 3,
 571.0: 4,
 572.0: 4,
 574.0: 2,
 576.0: 0,
 577.0: 5,
 578.0: 4,
 579.0: 1,
 580.0: 5,
 582.0: 1,
 583.0: 0,
 584.0: 5,
 586.0: 0,
 587.0: 5,
 588.0: 0,
 589.0: 1,
 590.0: 5,
 591.0: 0,
 592.0: 5,
 593.0: 0,
 594.0: 0,
 595.0: 5,
 598.0: 5,
 600.0: 5,
 601.0: 5,
 602.0: 5,
 603.0: 5,
 604.0: 5,
 605.0: 4,
 606.0: 5,
 607.0: 1,
 608.0: 2,
 609.0: 1,
 611.0: 0,
 612.0: 2,
 613.0: 5,
 614.0: 4,
 615.0: 4,
 616.0: 0,
 617.0: 1,
 618.0: 0,
 619.0: 5,
 620.0: 0,
 621.0: 4,
 622.0: 5,
 623.0: 0,
 624.0: 7,
 625.0: 4,
 626.0: 4,
 627.0: 5,
 628.0: 2,
 629.0: 4,
 630.0: 4,
 631.0: 0,
 632.0: 2,
 633.0: 0,
 634.0: 0,
 635.0: 0,
 636.0: 1,
 637.0: 0,
 638.0: 5,
 639.0: 2,
 640.0: 3,
 641.0: 2,
 642.0: 3,
 643.0: 3,
 644.0: 2,
 645.0: 3,
 646.0: 3,
 647.0: 3,
 648.0: 2,
 649.0: 3,
 650.0: 1,
 651.0: 2,
 652.0: 1,
 653.0: 2,
 654.0: 1}

In [58]:
nodes['partition'] = nodes['id'].apply(lambda x: partition[x])

In [60]:
# nodes.to_csv('nodes_for_voronoi.csv')

Once having the partition each node belongs to, the data can be exported to qgis to get the voronoi diagram for the telephone antennas. In this case, we used Qgis, but any other software or Python package can be used